spring:
  datasource:
    url: ${SUPERMARKET_DB_URL}
    username: ${SUPERMARKET_DB_USER_NAME}
    password: ${SUPERMARKET_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG